### ISSUE TITLE
Arquivos (Script.sql) para Mysql não encontrado

### ISSUE THREAD

**Issue by wilsonfr1975** [bjverde/adianti-fork-template#48]
no link aqui do Git  -> documents/changelog_fork_v7.3.0.md
Diz que  "O script sql do banco de permissões foi alterado para o MySQL Na pasta template/app/database/database_mysql/ tem 3 arquivos" , mas a pasta citada não existe .

**Comment by bjverde** [comment]
@wilsonfr1975 Desculpe a demora. 

Atualmente o adianti-fork-template está na versão 7.5.1b3, nessa versão realmente no existe o arquivo. Porém existe na versão 7.3.1 tem, no link abaixo ver os arquivos

https://github.com/bjverde/adianti-fork-template/tree/v7.3.0.1/template/app/database/database_mysql

Preciso atualizar o scripts para versão 7.5.1b3
